# Generated by Django 4.0.5 on 2022-06-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_pub_dat_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('choices', models.ManyToManyField(to='polls.choice')),
                ('questions', models.ManyToManyField(to='polls.question')),
            ],
        ),
    ]
